packages:
  - ui/**/*
  - bin

catalog:
  breakpoint-sass: github:WandererXII/breakpoint#4.1
  shogiground: ^0.10.3
  shogiops: ^0.21.0
  snabbdom: ^3.6.3

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - shogiops
  - shogiground
  - breakpoint-sass

onlyBuiltDependencies:
  - esbuild

savePrefix: ''
