packages:
  - ui/**/*
  - bin

catalog:
  shogiground: ^0.10.3
  shogiops: ^0.18.0
  '@badrap/result': ^0.2.13
  snabbdom: ^3.6.2
  breakpoint-sass: github:WandererXII/breakpoint#4.x

onlyBuiltDependencies:
  - esbuild
  - '@biomejs/biome'

savePrefix: ''
