packages:
  - ui/**/*
  - bin

catalog:
  '@badrap/result': ^0.2.13
  breakpoint-sass: github:WandererXII/breakpoint#4.x
  shogiground: ^0.10.3
  shogiops: ^0.19.0
  snabbdom: ^3.6.2

onlyBuiltDependencies:
  - esbuild
  - '@biomejs/biome'

savePrefix: ''
