// regions only if necessary

// langs we have on lishogi
const translated: Record<string, string> = {
  en: 'English',
  af: 'Afrikaans',
  ar: 'العربية',
  be: 'Беларуская',
  ca: 'Català, valencià',
  cs: 'čeština',
  da: 'Dansk',
  de: 'Deutsch',
  el: 'Ελληνικά',
  es: 'español',
  fa: 'فارسی',
  fi: 'suomen kieli',
  fr: 'français',
  gl: 'Galego',
  he: 'עִבְרִית',
  hi: 'हिन्दी, हिंदी',
  hu: 'Magyar',
  id: 'Bahasa Indonesia',
  it: 'Italiano',
  ja: '日本語',
  ko: '한국어',
  lt: 'lietuvių kalba',
  nb: 'Norsk bokmål',
  nl: 'Nederlands',
  pl: 'polski',
  pt: 'Português',
  ro: 'Română',
  ru: 'русский язык',
  sr: 'Српски језик',
  sv: 'svenska',
  th: 'ไทย',
  tl: 'Tagalog',
  tr: 'Türkçe',
  uk: 'українська',
  vi: 'Tiếng Việt',
  'zh-CN': '中文',
  'zh-TW': '繁體中文',
};

// other 'big' langs, that we do not have
const other: Record<string, string> = {
  as: 'অসমীয়া',
  az: 'Azərbaycanca',
  bg: 'български език',
  bn: 'বাংলা',
  br: 'brezhoneg',
  bs: 'bosanski',
  cv: 'чӑваш чӗлхи',
  cy: 'Cymraeg',
  eo: 'Esperanto',
  et: 'eesti keel',
  eu: 'Euskara',
  fo: 'føroyskt',
  frp: 'arpitan',
  fy: 'Frysk',
  ga: 'Gaeilge',
  gd: 'Gàidhlig',
  gu: 'ગુજરાતી',
  hr: 'hrvatski',
  hy: 'Հայերեն',
  ia: 'Interlingua',
  io: 'Ido',
  is: 'Íslenska',
  jbo: 'lojban',
  jv: 'basa Jawa',
  ka: 'ქართული',
  kab: 'Taqvaylit',
  kk: 'қазақша',
  kmr: 'Kurdî (Kurmancî)',
  kn: 'ಕನ್ನಡ',
  ky: 'кыргызча',
  la: 'lingua Latina',
  lv: 'latviešu valoda',
  mg: 'fiteny malagasy',
  mk: 'македонски јази',
  ml: 'മലയാളം',
  mn: 'монгол',
  mr: 'मराठी',
  ne: 'नेपाली',
  nn: 'Norsk nynorsk',
  pi: 'पालि',
  ps: 'پښتو',
  sa: 'संस्कृत',
  sk: 'slovenčina',
  sl: 'slovenščina',
  sq: 'Shqip',
  sw: 'Kiswahili',
  ta: 'தமிழ்',
  tg: 'тоҷикӣ',
  tk: 'Türkmençe',
  tp: 'toki pona',
  ur: 'اُردُو',
  uz: 'oʻzbekcha',
  yo: 'Yorùbá',
  zu: 'isiZulu',
};

export const allLangs: Record<string, string> = Object.entries({ ...translated, ...other })
  .sort(([a], [b]) => (a > b ? 1 : -1))
  .reduce(
    (acc, [key, value]) => {
      acc[key] = value;
      return acc;
    },
    {} as Record<string, string>,
  );
