name: Build assets

on:
  push:
    paths:
    - '.github/workflows/assets.yml'
    - 'public/**'
    - 'ui/**'
    - 'package.json'
    - 'yarn.lock'
  pull_request:
    paths:
    - '.github/workflows/assets.yml'
    - 'public/**'
    - 'ui/**'
    - 'package.json'
    - 'yarn.lock'

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: git submodule absorbgitdirs
    - run: echo "::set-output name=dir::$(yarn cache dir)"
      id: yarn-cache
    - uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-
    - run: ./ui/build prod
