name: Lint code

on:
  push:
    branches-ignore:
      - 'l10n_master2'
  pull_request:
    paths-ignore:
      - 'translation/dest/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - uses: github/codeql-action/init@v2
        with:
          languages: javascript, java
      - uses: github/codeql-action/analyze@v2
      - run: yarn install
      - run: yarn run lint
      - run: yarn run check-format
