name: Build ui

on:
  push:
    paths:
      - '.github/workflows/ui.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
  pull_request:
    paths:
      - '.github/workflows/ui.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get PNPM version from package.json
        id: pnpm-version
        shell: bash
        run: echo "pnpm_version=$(node -p 'require(`./package.json`).engines.pnpm')" >> $GITHUB_OUTPUT
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.pnpm-version.outputs.pnpm_version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: 'Install pnpm dependencies'
        run: pnpm install
      - name: 'Build'
        run: pnpm build:ui
      - name: 'Type check'
        run: pnpm type-check
      - name: 'Lint'
        run: pnpm lint
      - name: 'Format'
        run: pnpm format
